<style type="text/css">
	
	#wphb_message { margin-left:5px; }
	.wphb_clear { clear:both; }
	.wphb_form_field { width:770px; margin-bottom:5px; }
	.wphb_form_field .wphb_form_left { line-height:24px; font-weight:bold; width:350px; float:left; }
	.wphb_form_field .wphb_form_right { width:420px; float:left; position:relative; line-height:28px; }
	.wphb_form_field .wphb_form_right select, .wphb_form_field .wphb_form_right input { width:95%; }
	.wphb_form_field .wphb_form_right input.checkbox { width:auto !important; float:left; margin-left:2px; margin-top:5px; }
	.wphb_form_field .wphb_form_right p { padding:4px 0px 4px 6px; margin:0px; }
	.wphb_form { padding:10px; }
	.wphb_date { float:right; padding-right:5%; }
	.wphb_hinweis { font-style:italic; }
	
</style>			
			
<?php echo $this->writeBackendMessage(); ?>
	
<div class="wrap">
	<div id="icon-options-general" class="icon32">
		<br>
	</div>
	<h2><?php echo __('WpShopGermany - Händlerbund Integration', 'wphb'); ?></h2>
				
	<form method="POST" class="wphb_form">
		
		<?php echo $this->showForm(); ?>
		
		<div class="wphb_clear"></div>
		<br />
		<input type="submit" value="<?php echo __('Speichern', 'wphb'); ?>" name="wphb_submit" class="button-primary" />
		
	</form>
</div>